name: "jersey-mysql-redis"
description: "A sample java jersey stack"
template:
  type: "git"
  uri: 'https://github.com/aisensiy/javajersey_api.git'
tags:
    - "java"
languages:
  - name: "java"
    version: "1.8"
  - name: "xml"
    version: "4.0"
frameworks:
  - name: "jersey"
    version: "2.17"
  - name: "mybatis"
    version: "3.3"
tools:
  - name: "gradle"
    version: "2.8"
services:
  web:
    build:
      image: '192.168.99.100:5000/javajersey-build'
      mem: 512
      cpus: 0.5
    verify:
      image: '192.168.99.100:5000/javajersey-verify'
      mem: 512
      cpus: 0.5
    main: yes
    mem: 512
    cpus: 0.4
    instances: 1
    links:
      - db
      - redis
    expose: 8088
    health:
      - protocol: "COMMAND"
        command: "exit 0"
        interval: "3"
        timeout: "2"
    environment:
      DB_NAME: 'data_store'
  db:
    mem: 256
    instances: 1
    cpus: 0.2
    image: "mysql"
    environment:
      MYSQL_ROOT_PSSWORD: "mysql"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "data_store"
    expose: 3306
    volumes:
      - data:/var/lib/mysql
    health:
      - protocol: "COMMAND"
        interval: "3"
        timeout: "2"
        command: "exit 0"
  redis:
    mem: 256
    instances: 1
    cpus: 0.2
    image: redis
    expose: 6379
    volumes:
      - data:/data
    health:
      - protocol: "COMMAND"
        interval: "3"
        timeout: "2"
        command: "exit 0"

