name: "jersey-mysql-redis"
description: "A sample java jersey stack"
template:
  type: "git"
  uri: 'https://github.com/aisensiy/javajersey_api.git'
tags:
    - "java"
languages:
  - name: "java"
    version: "1.8"
  - name: "xml"
    version: "4.0"
frameworks:
  - name: "jersey"
    version: "2.17"
  - name: "mybatis"
    version: "3.3"
tools:
  - name: "gradle"
    version: "2.8"
services:
  web:
    build:
      image: 'hub.deepi.cn/javajersey-build'
      mem: 512
      cpus: 0.5
    verify:
      image: 'hub.deepi.cn/javajersey-verify'
      mem: 512
      cpus: 0.5
    main: yes
    mem: 512
    cpus: 0.2
    instances: 1
    links:
      - db
      - redis
    expose: 8088
    health:
      - protocol: "COMMAND"
        command: "exit 0"
        interval: "3"
        timeout: "2"
    environment:
      DB_NAME: 'data_store'
      SERVICE_PORT: '8088'
      DB_USERNAME: 'mysql'
      DB_PASSWORD: 'mysql'
  db:
    mem: 512
    instances: 1
    cpus: 0.2
    image: "tutum/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_USER: "mysql"
      MYSQL_PASS: "mysql"
      ON_CREATE_DB: "data_store"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "data_store"
      EXTRA_OPTS: "--lower_case_table_names=1"
    expose: 3306
    volumes:
      - db:/var/lib/mysql
    health:
      - protocol: "COMMAND"
        command: "exit 0"
        interval: "3"
        timeout: "2"
  redis:
    mem: 256
    instances: 1
    cpus: 0.2
    image: redis
    expose: 6379
    volumes:
      - redis:/data
    health:
      - protocol: "TCP"
        portIndex: 0
        interval: 5
        timeout: 5
        grace: 120
        maxConsecutiveFailures: 10

