name: "jersey-mysql"
description: "A sample java jersey stack"
template:
  type: "git"
  uri: 'https://github.com/aisensiy/cde-jersey-mysql-init-project.git'
tags:
    - "java"
languages:
  - name: "java"
    version: "1.8"
frameworks:
  - name: "jersey"
    version: "2.17"
  - name: "mybatis"
    version: "3.3"
tools:
  - name: "gradle"
    version: "2.8"
services:
  web:
    build:
      image: 'hub.deepi.cn/jersey-mysql-build'
      mem: 512
      cpus: 0.5
    verify:
      image: 'hub.deepi.cn/jersey-mysql-verify'
      mem: 512
      cpus: 0.5
    main: yes
    mem: 512
    cpus: 0.2
    instances: 1
    links:
      - db
    expose: 8088
    environment:
      SERVICE_PORT: 8088
      DB_NAME: 'data_store'
      DB_USERNAME: 'mysql'
      DB_PASSWORD: 'mysql'
    health:
      - protocol: "TCP"
        portIndex: 0
        interval: 3
        timeout: 2
        grace: 2
        maxConsecutiveFailures: 2
  db:
    mem: 512
    instances: 1
    cpus: 0.2
    image: "tutum/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_USER: "mysql"
      MYSQL_PASS: "mysql"
      ON_CREATE_DB: "data_store"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "data_store"
      EXTRA_OPTS: "--lower_case_table_names=1"
    expose: 3306
    volumes:
      - db:/var/lib/mysql
    health:
      - protocol: "TCP"
        portIndex: 0
        interval: 3
        timeout: 2
        grace: 2
        maxConsecutiveFailures: 2
