name: "flask"
description: "A flask stack"
template:
  type: "git"
  uri: 'https://github.com/aisensiy/cde-flask-init-project.git'
tags:
    - "python"
languages:
  - name: "python"
frameworks:
  - name: "flask"
tools:
services:
  main:
    build:
      image: 'hub.deepi.cn/flask-build'
      mem: 512
      cpus: 0.5
    verify:
      image: 'hub.deepi.cn/flask-verify'
      mem: 512
      cpus: 0.5
    main: yes
    mem: 512
    cpus: 0.2
    instances: 1
    expose: 5000
    volumes:
      - db:/data
    health:
      - protocol: "COMMAND"
        command: "exit 0"
        interval: "3"
        timeout: "2"
