name: "create-react-app"
description: "A react webpack stack"
template:
  type: "git"
  uri: 'https://github.com/aisensiy/javajersey_api.git'
tags:
    - "react"
languages:
  - name: "react"
frameworks:
  - name: "react"
tools:
  - name: "webpack"
services:
  web:
    build:
      image: 'hub.deepi.cn/create-react-app-build'
      mem: 512
      cpus: 0.5
    verify:
      image: 'hub.deepi.cn/react-verify'
      mem: 512
      cpus: 0.5
    main: yes
    mem: 512
    cpus: 0.1
    instances: 1
    expose: 9000
    environment:
      SERVICE_PORT: '9000'
    health:
      - protocol: "TCP"
        portIndex: 0
        interval: 5
        timeout: 5
        grace: 120
        maxConsecutiveFailures: 10
